project:
  type: website
  output-dir: "_output"

date-format: iso
# theme:
#   # https://quarto.org/docs/output-formats/html-themes.html
#   light: flatly
#   dark: darkly

website:
  title: "quarto-slides"
  navbar: true
