project:
  type: website
  output-dir: "_output"

date-format: iso

website:
  title: "quarto-slides"
  navbar: true
  search: false

format:
  revealjs:
    code-copy: true
    code-overflow: wrap
    scrollable: true
    self-contained: true
    slide-level: 3
    slide-number: true
    theme:
      - default
      - custom.scss
    width: 1920
    height: 1080
    title-slide-attributes:
      data-background-color: "#001722"  # Dark Navy
      data-background-image: "/assets/common/title-background.png"
      data-background-size: "cover"
